[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:7
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE0 turned ON
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE0, cpu:1.16666666667 ram:1.16666666667
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE0, for: i-53390A93 with tax:1.16666666667
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE0, cpu:1.83333333333 ram:1.83333333333
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE0, for: i-56CB0910 with tax:1.5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:128933, lastCicle:130000, len(op_dict):1787
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:20
[INFO] 	main.py->run_test_chave: 	 New max host on: 146 at 128933 sec.
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE1 turned ON
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE1 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4811094D, from NODE1
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:132391, lastCicle:134000, len(op_dict):1785
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:21
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE1 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:138218, lastCicle:140000, len(op_dict):1775
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:31
[INFO] 	main.py->run_test_chave: 	 New max host on: 265 at 138218 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-310005BF, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CD1084F, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3FC3072C, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44760829, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47CB0883, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-49F207B6, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-52AF08F8, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-538A0978, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-55E109F1, from NODE1
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE1 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4DC408FF, from NODE1
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:142108, lastCicle:144000, len(op_dict):1765
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:31
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE1 turned ON
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-251904E8, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40F1081F, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-413E07EA, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-42D607E1, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4339080A, from NODE1
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE1 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5D780AE6, from NODE1
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE1 turned ON
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-36B40618, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3D970701, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3F9D07AE, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43BD0804, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4DAC0839, from NODE1
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE1 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-441807EE, from NODE1
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE1 turned ON
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE1 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47D108B4, from NODE1
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:150687, lastCicle:152000, len(op_dict):1739
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:44
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE1 turned ON
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41D406F5, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46B10871, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-474207D4, from NODE1
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE1 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-53850A24, from NODE1
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:152099, lastCicle:154000, len(op_dict):1731
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:48
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE1 turned ON
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4AD908C4, from NODE1
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5B8F09B7, from NODE1
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE1 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3031067B, from NODE1
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:398358, lastCicle:400000, len(op_dict):1725
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:51
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE1 turned ON
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE1, cpu:2.0 ram:2.0
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE1, for: i-3BB406AD with tax:2.0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:448393, lastCicle:450000, len(op_dict):1723
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:53
[INFO] 	main.py->run_test_chave: 	 New max host on: 485 at 448393 sec.
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE1 cpu:12...
[DEBUG] 	Physical.py->deallocate: 	 		DONE! NODE1 has no overb.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3BB406AD, from NODE1
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE1 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4DE4083C, from NODE1
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:461340, lastCicle:462000, len(op_dict):1721
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:53
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE2 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:462679, lastCicle:464000, len(op_dict):1720
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:54
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE2 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48B50909, from NODE2
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE2 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:481512, lastCicle:482000, len(op_dict):1716
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:57
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A6308A7, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-428C075D, from NODE2
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE2 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47D107DD, from NODE2
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE2 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:487566, lastCicle:488000, len(op_dict):1703
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:67
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3AFD06E4, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3D4F076C, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4462077C, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-457107EB, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-49EE07FA, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A9A08B1, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4AF7082A, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-522C0905, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-473008BF, from NODE2
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE2 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48B70831, from NODE2
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:501698, lastCicle:502000, len(op_dict):1693
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:67
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE2 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:507706, lastCicle:508000, len(op_dict):1692
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:68
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE2 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E1907C6, from NODE2
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:635336, lastCicle:636000, len(op_dict):1691
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:68
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE2 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:639332, lastCicle:640000, len(op_dict):1687
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:72
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-34AE0597, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4BBF08C7, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A9506E2, from NODE2
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE2 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4F2508D1, from NODE2
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:646674, lastCicle:648000, len(op_dict):1683
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:72
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE2 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:661818, lastCicle:662000, len(op_dict):1673
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:82
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-35A4071E, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-383906F2, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A1C06C8, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C61076A, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3EA80764, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4005071B, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-450A07E4, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A9E08A5, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4981089D, from NODE2
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE2 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4D1008F7, from NODE2
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:1088789, lastCicle:1090000, len(op_dict):1663
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:82
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE2 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:1090329, lastCicle:1092000, len(op_dict):1658
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:87
[INFO] 	main.py->run_test_chave: 	 New max host on: 4938 at 1090329 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-377B0665, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-450408E8, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47440810, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-49730931, from NODE2
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE2 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4AD008CD, from NODE2
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:1351182, lastCicle:1352000, len(op_dict):1653
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:87
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE2 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:1444819, lastCicle:1446000, len(op_dict):1652
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:88
[INFO] 	main.py->run_test_chave: 	 New max host on: 5038 at 1444819 sec.
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE2 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4FB808E2, from NODE2
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:1674003, lastCicle:1676000, len(op_dict):1651
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:88
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE2 turned ON
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3762068A, from NODE2
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46D8083F, from NODE2
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE2 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-52DF085D, from NODE2
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE2 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2196474, lastCicle:2198000, len(op_dict):1644
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:92
[INFO] 	main.py->run_test_chave: 	 New max host on: 5438 at 2196474 sec.
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE2, cpu:1.08333333333 ram:1.08333333333
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE2, for: i-318B0633 with tax:1.08333333333
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE3 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2236236, lastCicle:2238000, len(op_dict):1642
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:94
[INFO] 	main.py->run_test_chave: 	 New max host on: 5737 at 2236236 sec.
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE3 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4AF908B3, from NODE3
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE2 cpu:23...
[DEBUG] 	Physical.py->deallocate: 	 		DONE! NODE2 has no overb.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-318B0633, from NODE2
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2275680, lastCicle:2276000, len(op_dict):1640
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:94
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE3 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2296439, lastCicle:2298000, len(op_dict):1639
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:95
[INFO] 	main.py->run_test_chave: 	 New max host on: 5837 at 2296439 sec.
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE2 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-34DA07B1, from NODE2
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE3, cpu:1.08333333333 ram:1.08333333333
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE3, for: i-424307D5 with tax:1.08333333333
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE3, cpu:1.16666666667 ram:1.16666666667
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE3, for: i-547D098B with tax:1.08333333333
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2316395, lastCicle:2318000, len(op_dict):1636
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:97
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE3 cpu:1...
[DEBUG] 	Physical.py->deallocate: 	 		DONE! NODE3 has no overb.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-424307D5, from NODE3
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-547D098B, from NODE3
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE3, cpu:1.25 ram:1.25
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE3, for: i-522C08DB with tax:1.08333333333
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2320372, lastCicle:2322000, len(op_dict):1631
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:100
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE4 turned ON
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE4, cpu:2.0 ram:2.0
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE4, for: i-4DD408BB with tax:2.0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2326269, lastCicle:2328000, len(op_dict):1629
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:102
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE3 cpu:1...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:13 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46B407F5, from NODE3
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE3 cpu:2...
[DEBUG] 	Physical.py->deallocate: 	 		DONE! NODE3 has no overb.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4707079C, from NODE3
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-522C08DB, from NODE3
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2365893, lastCicle:2366000, len(op_dict):1626
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:102
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2366240, lastCicle:2368000, len(op_dict):1625
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:103
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4E130834, from NODE3
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A8806C0, from NODE3
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3EBB082A, from NODE3
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2378056, lastCicle:2380000, len(op_dict):1620
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:105
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-55810B0B, from NODE3
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2386390, lastCicle:2388000, len(op_dict):1617
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:107
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48620893, from NODE3
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2405083, lastCicle:2406000, len(op_dict):1616
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:107
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE4 cpu:12...
[DEBUG] 	Physical.py->deallocate: 	 		DONE! NODE4 has no overb.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4DD408BB, from NODE4
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE4 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4EBB095F, from NODE4
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE3 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43AE081B, from NODE3
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2473423, lastCicle:2474000, len(op_dict):1613
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:107
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE0 cpu:1...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:13 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43FD0797, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2805374, lastCicle:2806000, len(op_dict):1612
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:107
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2807333, lastCicle:2808000, len(op_dict):1611
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:108
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE0 cpu:1...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:13 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3BD7078A, from NODE0
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE0 cpu:1...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:13 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46CF08BA, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2890185, lastCicle:2892000, len(op_dict):1608
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:109
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE5 turned ON
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE5 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4654088A, from NODE5
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE5 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2893381, lastCicle:2894000, len(op_dict):1605
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:111
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE5 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-403307F0, from NODE5
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE5 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:2993256, lastCicle:2994000, len(op_dict):1603
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:112
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE5, cpu:1.16666666667 ram:1.16666666667
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE5, for: i-4E01092F with tax:1.16666666667
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE5, cpu:1.5 ram:1.5
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE5, for: i-51A20A6F with tax:1.16666666667
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE5, cpu:1.83333333333 ram:1.83333333333
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE5, for: i-54D7099C with tax:1.16666666667
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE6, cpu:1.33333333333 ram:1.33333333333
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE6, for: i-3B1C0671 with tax:1.33333333333
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE6, cpu:1.66666666667 ram:1.66666666667
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE6, for: i-40FD0734 with tax:1.33333333333
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE6, cpu:2.0 ram:2.0
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE6, for: i-4DCE08E7 with tax:1.33333333333
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE3 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3012398, lastCicle:3014000, len(op_dict):1591
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:124
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE6 cpu:4...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:16 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3B1C0671, from NODE6
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE6 cpu:8...
[DEBUG] 	Physical.py->deallocate: 	 		DONE! NODE6 has no overb.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3F2407E4, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40FD0734, from NODE6
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE3 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48BF0863, from NODE3
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE5 cpu:6...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:18 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4B280810, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4DCE08E7, from NODE6
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE5 cpu:10...
[DEBUG] 	Physical.py->deallocate: 	 		DONE! NODE5 has no overb.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4E01092F, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-51A20A6F, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-51EE09B8, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-54D7099C, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5B8F0A33, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2DD806F4, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3049515, lastCicle:3050000, len(op_dict):1579
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:124
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE3 turned ON
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE3, cpu:1.33333333333 ram:1.33333333333
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE3, for: i-318205A9 with tax:1.08333333333
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE3, cpu:1.66666666667 ram:1.66666666667
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE3, for: i-46CE0860 with tax:1.08333333333
[DEBUG] 	Physical.py->can_overbooking: 	 WE can do overb on:NODE3, cpu:2.0 ram:2.0
[DEBUG] 	Physical.py->do_overbooking: 	 Do Overb on:NODE3, for: i-490D0816 with tax:1.08333333333
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3055310, lastCicle:3056000, len(op_dict):1567
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:136
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE3 cpu:7...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:19 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-302606C9, from NODE3
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE3 cpu:11...
[DEBUG] 	Physical.py->deallocate: 	 		DONE! NODE3 has no overb.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-318205A9, from NODE3
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-367C06F2, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-372F06E1, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-376608AD, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46CE0860, from NODE3
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-490D0816, from NODE3
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3DA60759, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4AAD0791, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5325095B, from NODE3
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-492A07F6, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3056572, lastCicle:3058000, len(op_dict):1556
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:136
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE3 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4071075A, from NODE3
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3058502, lastCicle:3060000, len(op_dict):1555
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:136
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-315706B4, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-36B106D7, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-473E073B, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3060556, lastCicle:3062000, len(op_dict):1549
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:139
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-527E08C5, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3063281, lastCicle:3064000, len(op_dict):1547
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:140
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE4 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3064132, lastCicle:3066000, len(op_dict):1535
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:152
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-36380695, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39ED0677, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CAA0691, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CC00675, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3EA007B3, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4AEC0781, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4B9207FD, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4CD9087E, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4F570838, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE4 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4B2008A8, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4F0B08AE, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5423086C, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3068279, lastCicle:3070000, len(op_dict):1523
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:152
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-32AA06A8, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E4C0755, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43A70776, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-34B906DE, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3DC506F6, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3070328, lastCicle:3072000, len(op_dict):1513
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:157
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE0 cpu:1...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:13 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-542D0A09, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4272087C, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3144398, lastCicle:3146000, len(op_dict):1509
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:159
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3159920, lastCicle:3160000, len(op_dict):1508
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:160
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE0 cpu:1...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:13 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39050728, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3160930, lastCicle:3162000, len(op_dict):1507
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:160
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE0 cpu:2...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:14 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E9A0864, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3414407, lastCicle:3416000, len(op_dict):1506
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:160
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE0 cpu:2...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:14 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4C610977, from NODE0
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE0 cpu:1...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:13 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-50510914, from NODE0
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE0 cpu:2...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:14 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4127082C, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3422678, lastCicle:3424000, len(op_dict):1500
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:163
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:3424092, lastCicle:3426000, len(op_dict):1499
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:164
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE0 cpu:2...
[DEBUG] 	Physical.py->deallocate: 	 		Not yet:14 still > 12
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48440901, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:4548296, lastCicle:4550000, len(op_dict):1498
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:164
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:4702360, lastCicle:4704000, len(op_dict):1496
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:166
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4933088E, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:4707485, lastCicle:4708000, len(op_dict):1494
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:167
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:4715032, lastCicle:4716000, len(op_dict):1493
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:168
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-495B0801, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:4787644, lastCicle:4788000, len(op_dict):1490
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:170
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-449706EF, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:4980851, lastCicle:4982000, len(op_dict):1489
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:170
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E9A07C7, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:4982512, lastCicle:4984000, len(op_dict):1486
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:172
[INFO] 	main.py->run_test_chave: 	 New max host on: 59113 at 4982512 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46A608C7, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:5157076, lastCicle:5158000, len(op_dict):1485
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:172
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3DEA07A4, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3502063D, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:5163479, lastCicle:5164000, len(op_dict):1480
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:175
[INFO] 	main.py->run_test_chave: 	 New max host on: 62113 at 5163479 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:5164619, lastCicle:5166000, len(op_dict):1479
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:176
[INFO] 	main.py->run_test_chave: 	 New max host on: 63113 at 5164619 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-376406A8, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C0606A9, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:5237691, lastCicle:5238000, len(op_dict):1477
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:176
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:5238335, lastCicle:5240000, len(op_dict):1476
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:177
[INFO] 	main.py->run_test_chave: 	 New max host on: 64113 at 5238335 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-32970668, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:5240427, lastCicle:5242000, len(op_dict):1474
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:178
[INFO] 	main.py->run_test_chave: 	 New max host on: 65113 at 5240427 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C1107CC, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:5573966, lastCicle:5574000, len(op_dict):1473
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:178
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6004341, lastCicle:6006000, len(op_dict):1472
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:179
[INFO] 	main.py->run_test_chave: 	 New max host on: 66113 at 6004341 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6293425, lastCicle:6294000, len(op_dict):1471
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:180
[INFO] 	main.py->run_test_chave: 	 New max host on: 67113 at 6293425 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6296212, lastCicle:6298000, len(op_dict):1470
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:181
[INFO] 	main.py->run_test_chave: 	 New max host on: 68113 at 6296212 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47E807DD, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6299441, lastCicle:6300000, len(op_dict):1468
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:182
[INFO] 	main.py->run_test_chave: 	 New max host on: 69113 at 6299441 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-392B0670, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6333707, lastCicle:6334000, len(op_dict):1467
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:182
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6334196, lastCicle:6336000, len(op_dict):1466
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:183
[INFO] 	main.py->run_test_chave: 	 New max host on: 70113 at 6334196 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E8207B0, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6338020, lastCicle:6340000, len(op_dict):1464
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:184
[INFO] 	main.py->run_test_chave: 	 New max host on: 71113 at 6338020 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CA8076B, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6341596, lastCicle:6342000, len(op_dict):1462
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:185
[INFO] 	main.py->run_test_chave: 	 New max host on: 72113 at 6341596 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43E60772, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6517042, lastCicle:6518000, len(op_dict):1461
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:185
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-382B088E, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6520968, lastCicle:6522000, len(op_dict):1459
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:186
[INFO] 	main.py->run_test_chave: 	 New max host on: 73113 at 6520968 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6526199, lastCicle:6528000, len(op_dict):1458
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:187
[INFO] 	main.py->run_test_chave: 	 New max host on: 74113 at 6526199 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A7708B7, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6543887, lastCicle:6544000, len(op_dict):1456
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:188
[INFO] 	main.py->run_test_chave: 	 New max host on: 75113 at 6543887 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-33CA0683, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6552306, lastCicle:6554000, len(op_dict):1455
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:188
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6557501, lastCicle:6558000, len(op_dict):1454
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:189
[INFO] 	main.py->run_test_chave: 	 New max host on: 76113 at 6557501 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44E907C8, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6603552, lastCicle:6604000, len(op_dict):1453
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:189
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6608085, lastCicle:6610000, len(op_dict):1452
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:190
[INFO] 	main.py->run_test_chave: 	 New max host on: 77113 at 6608085 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-33BF069D, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-501708F6, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6611833, lastCicle:6612000, len(op_dict):1449
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:191
[INFO] 	main.py->run_test_chave: 	 New max host on: 78113 at 6611833 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6694967, lastCicle:6696000, len(op_dict):1448
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:192
[INFO] 	main.py->run_test_chave: 	 New max host on: 79113 at 6694967 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-54050914, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6699915, lastCicle:6700000, len(op_dict):1446
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:193
[INFO] 	main.py->run_test_chave: 	 New max host on: 80113 at 6699915 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6700574, lastCicle:6702000, len(op_dict):1445
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:194
[INFO] 	main.py->run_test_chave: 	 New max host on: 81113 at 6700574 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44FE0891, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-422C0817, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6705752, lastCicle:6706000, len(op_dict):1442
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:195
[INFO] 	main.py->run_test_chave: 	 New max host on: 82113 at 6705752 sec.
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6706715, lastCicle:6708000, len(op_dict):1441
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:196
[INFO] 	main.py->run_test_chave: 	 New max host on: 9799 at 6706715 sec.
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39B606DA, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6708348, lastCicle:6710000, len(op_dict):1439
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:197
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3F1D076D, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-502608D5, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44BC08B2, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6769093, lastCicle:6770000, len(op_dict):1435
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:198
[DEBUG] 	Physical.py->deallocate: 	 Undo overb:NODE0 cpu:8...
[DEBUG] 	Physical.py->deallocate: 	 		DONE! NODE0 has no overb.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-56CB0910, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-53390A93, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6770418, lastCicle:6772000, len(op_dict):1432
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:199
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41F40789, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E9D083D, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39640730, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-51200A84, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6772187, lastCicle:6774000, len(op_dict):1425
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:202
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3EAA0690, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-424E072B, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-478507B4, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6774074, lastCicle:6776000, len(op_dict):1418
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:206
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-477C08FD, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:6782583, lastCicle:6784000, len(op_dict):1417
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:206
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CD50694, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7050649, lastCicle:7052000, len(op_dict):1415
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:207
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7078270, lastCicle:7080000, len(op_dict):1414
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:208
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5A910999, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7131561, lastCicle:7132000, len(op_dict):1413
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:208
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7132202, lastCicle:7134000, len(op_dict):1408
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:213
[INFO] 	main.py->run_test_chave: 	 New max host on: 99114 at 7132202 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-348905FA, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-45F707CC, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4709089C, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47E00826, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2E240567, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-439908A1, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7136258, lastCicle:7138000, len(op_dict):1400
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:215
[INFO] 	main.py->run_test_chave: 	 New max host on: 101114 at 7136258 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-38580685, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7173419, lastCicle:7174000, len(op_dict):1399
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:215
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4D310898, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7202625, lastCicle:7204000, len(op_dict):1398
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:215
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C6C0732, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7302195, lastCicle:7304000, len(op_dict):1397
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:215
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7307419, lastCicle:7308000, len(op_dict):1396
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:216
[INFO] 	main.py->run_test_chave: 	 New max host on: 102114 at 7307419 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7400029, lastCicle:7402000, len(op_dict):1395
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:217
[INFO] 	main.py->run_test_chave: 	 New max host on: 103114 at 7400029 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CBF065B, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7733837, lastCicle:7734000, len(op_dict):1393
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:218
[INFO] 	main.py->run_test_chave: 	 New max host on: 104114 at 7733837 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3FE00720, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7734379, lastCicle:7736000, len(op_dict):1392
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:218
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47A7089E, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-429007DC, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7736277, lastCicle:7738000, len(op_dict):1387
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:221
[INFO] 	main.py->run_test_chave: 	 New max host on: 107114 at 7736277 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4DC3090A, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7744901, lastCicle:7746000, len(op_dict):1386
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:221
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46B9081D, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:7916652, lastCicle:7918000, len(op_dict):1385
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:221
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-312906D9, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-513E07ED, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8002280, lastCicle:8004000, len(op_dict):1382
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:222
[INFO] 	main.py->run_test_chave: 	 New max host on: 108114 at 8002280 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8006040, lastCicle:8008000, len(op_dict):1378
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:226
[INFO] 	main.py->run_test_chave: 	 New max host on: 112114 at 8006040 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-321E067D, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-45E60826, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46E5088D, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-49F508ED, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5326086C, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4AE60838, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8017399, lastCicle:8018000, len(op_dict):1371
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:227
[INFO] 	main.py->run_test_chave: 	 New max host on: 113114 at 8017399 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8019555, lastCicle:8020000, len(op_dict):1361
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:237
[INFO] 	main.py->run_test_chave: 	 New max host on: 123114 at 8019555 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8021248, lastCicle:8022000, len(op_dict):1357
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:241
[INFO] 	main.py->run_test_chave: 	 New max host on: 127114 at 8021248 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8025362, lastCicle:8026000, len(op_dict):1354
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:244
[INFO] 	main.py->run_test_chave: 	 New max host on: 130114 at 8025362 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-331E0693, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-365105FC, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-36E50759, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-38DC06BF, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3BDA07D5, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3BFE073E, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C8D081D, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E6A07BA, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4159076B, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41CD077D, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4297077E, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4467083C, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A3807C5, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4DB508FC, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4E1908BA, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3D2C07C4, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48FF0875, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8063147, lastCicle:8064000, len(op_dict):1337
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:244
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8066823, lastCicle:8068000, len(op_dict):1324
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:257
[INFO] 	main.py->run_test_chave: 	 New max host on: 15899 at 8066823 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-312C0643, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-32EB05B1, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-359D068B, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C5C0827, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3D1A0810, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44B40623, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46D307C6, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48250945, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-491407CD, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4D3D093D, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-58B30923, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3514072B, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-45F8091C, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8068734, lastCicle:8070000, len(op_dict):1311
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:257
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8074833, lastCicle:8076000, len(op_dict):1310
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:258
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4DA1097A, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8175000, lastCicle:8176000, len(op_dict):1309
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:258
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2F0A066B, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-449E07F8, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-45E6075A, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47BA088B, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2F6906B1, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-35EE0656, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A2407CA, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-59130A5B, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-409D0809, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-400C0860, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-467D07D1, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-510E090C, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-589A0989, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-380705D2, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41F207D8, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-468408C8, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8236207, lastCicle:8238000, len(op_dict):1277
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:274
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8265729, lastCicle:8266000, len(op_dict):1250
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:301
[INFO] 	main.py->run_test_chave: 	 New max host on: 20299 at 8265729 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8266081, lastCicle:8268000, len(op_dict):1249
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:302
[INFO] 	main.py->run_test_chave: 	 New max host on: 20399 at 8266081 sec.
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE4 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8269158, lastCicle:8270000, len(op_dict):1245
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:306
[INFO] 	main.py->run_test_chave: 	 New max host on: 21195 at 8269158 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2D610620, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-33EB069A, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39250802, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39A6077F, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3AA20709, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3AFB074D, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C060728, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CC30698, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3ED306B2, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3F9B07A1, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-400D0743, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40270775, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40C8079F, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47FC087F, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4B0208C2, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4F560968, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-51E608E8, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-51F40917, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-52E30967, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-54B40980, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-58AA0A50, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4147081B, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4179084E, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41890720, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-42180875, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-426608E7, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4297089C, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43C307B8, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46200877, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4D9C0900, from NODE6
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2A8C05B6, from NODE6
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE4 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5120099A, from NODE4
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8278370, lastCicle:8280000, len(op_dict):1213
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:306
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-336E066A, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-33B206BA, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39050788, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3AC00686, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3B0106EC, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C0707DB, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C7F074C, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E1406F3, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3EB30855, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3F9C072A, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-407A07B0, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41C007F0, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44C6086D, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-45E40900, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-45EE0791, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A1A0800, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A96083E, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4BAD0853, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4EFA083E, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-500409A6, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-502E08BF, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-509C09C2, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-51460982, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-55570943, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-56CA0A61, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5AB808C4, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-453F0880, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A6D0815, from NODE6
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-483C0862, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8321456, lastCicle:8322000, len(op_dict):1155
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:335
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE4 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8322104, lastCicle:8324000, len(op_dict):1125
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:365
[INFO] 	main.py->run_test_chave: 	 New max host on: 27095 at 8322104 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8329004, lastCicle:8330000, len(op_dict):1120
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:370
[INFO] 	main.py->run_test_chave: 	 New max host on: 27595 at 8329004 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2D0305AD, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-30B00681, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-311A05C9, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-32C606B8, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-347E073E, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-369D07DB, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39070700, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39C606F1, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A6A06C9, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C1A0732, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C290777, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3D0507CF, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3FE90793, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48F007FD, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4966083D, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-496E07DB, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-498A07FE, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A530896, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4AD70742, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4C230853, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-50BB0901, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-50F3097C, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-566B094B, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-59B60A00, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3FF90784, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-412A0840, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41BE078F, from NODE6
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE4 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41DA088D, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4373087E, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43AF070E, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-448207CC, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44B70820, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44F40832, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4699078F, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5E670A26, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8330123, lastCicle:8332000, len(op_dict):1085
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:370
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8336219, lastCicle:8338000, len(op_dict):1084
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:371
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4467084F, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8344907, lastCicle:8346000, len(op_dict):1082
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:372
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-31070562, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8841978, lastCicle:8842000, len(op_dict):1081
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:372
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8842058, lastCicle:8844000, len(op_dict):1080
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:373
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8861178, lastCicle:8862000, len(op_dict):1071
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:382
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2BF40519, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-35DF05DB, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3D850776, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E60066B, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40710779, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-417507C7, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-490B08DD, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-501E0A22, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5227099E, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-443F0740, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8944378, lastCicle:8946000, len(op_dict):1061
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:382
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:8951527, lastCicle:8952000, len(op_dict):1059
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:384
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-327A05CE, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46300836, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9026501, lastCicle:9028000, len(op_dict):1057
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:384
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4DE008AA, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9031875, lastCicle:9032000, len(op_dict):1055
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:385
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9032098, lastCicle:9034000, len(op_dict):1049
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:391
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9040418, lastCicle:9042000, len(op_dict):1035
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:405
[INFO] 	main.py->run_test_chave: 	 New max host on: 297108 at 9040418 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2EFE0644, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-336306BF, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3527067E, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-398507BA, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40810737, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41A30787, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-42A107C8, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43E607B9, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-456307B2, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-457C0774, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-49FE086A, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4FE10912, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-51C60926, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-60C709E3, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C6F06BE, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39530766, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-492008E4, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4F700816, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-523909BC, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-67E60C3E, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9051170, lastCicle:9052000, len(op_dict):1015
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:405
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9052679, lastCicle:9054000, len(op_dict):1013
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:407
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3FB90811, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-453C0895, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9059852, lastCicle:9060000, len(op_dict):1011
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:407
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9060800, lastCicle:9062000, len(op_dict):1009
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:409
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46F007F8, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9064314, lastCicle:9066000, len(op_dict):1005
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:412
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3D6A07AD, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5530099A, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9190662, lastCicle:9192000, len(op_dict):1003
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:412
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2DFD05B3, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-452708DC, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40380787, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-38670769, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-519E089B, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-56DC0926, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9192072, lastCicle:9194000, len(op_dict):993
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:416
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-510E0981, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9199581, lastCicle:9200000, len(op_dict):991
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:417
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46140865, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-527B0978, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9200022, lastCicle:9202000, len(op_dict):987
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:419
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-527909D2, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2C4F04F9, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2C90059C, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5AD90A08, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48C1095A, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-60730AE6, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3F1C0721, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40AE07DB, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9211524, lastCicle:9212000, len(op_dict):971
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:427
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-322305ED, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3BB00795, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-487A080B, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2AB905A5, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E570717, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5486090D, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3ABF0711, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40A907B7, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9212359, lastCicle:9214000, len(op_dict):955
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:435
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-22F303E2, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-36300757, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-418D0680, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4397087B, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C41085E, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CC80737, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3FE30738, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-42AC0867, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C6106B6, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44AE079F, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46FA0881, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9282272, lastCicle:9284000, len(op_dict):932
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:447
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A9D060C, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9284623, lastCicle:9286000, len(op_dict):929
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:449
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-32A10684, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9289770, lastCicle:9290000, len(op_dict):928
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:449
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9293820, lastCicle:9294000, len(op_dict):927
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:450
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9294149, lastCicle:9296000, len(op_dict):925
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:452
[INFO] 	main.py->run_test_chave: 	 New max host on: 344108 at 9294149 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-320906C9, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-452308C1, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48CD078D, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-430D0805, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4806082F, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-365705DB, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-441C080D, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-461A08D7, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-33B30626, from NODE0
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE4 turned ON
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-35030642, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A1607F6, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-42CE07FC, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4CC80969, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4EFE08B5, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-35B3061E, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE4 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3BA706B9, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4FE90848, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9296645, lastCicle:9298000, len(op_dict):891
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:469
[INFO] 	main.py->run_test_chave: 	 New max host on: 358111 at 9296645 sec.
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE4 turned ON
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C83071B, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E11079F, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-45F708B3, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4BE107FB, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4F80088B, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-446608B9, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4C2508CF, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE4 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-53740973, from NODE4
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9298025, lastCicle:9300000, len(op_dict):875
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:477
[INFO] 	main.py->run_test_chave: 	 New max host on: 363114 at 9298025 sec.
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE4 turned ON
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-408107C1, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-438B08E7, from NODE4
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE4 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4E170A2D, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4E2F0869, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-56470949, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-31E40680, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-33AC0740, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-42BF07D0, from NODE5
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE4 turned ON
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E990753, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-452407BB, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A6608C9, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4BCA0867, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4C450853, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-35BB060C, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3BB3075C, from NODE4
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE4 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CE207E1, from NODE4
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9300168, lastCicle:9302000, len(op_dict):843
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:493
[INFO] 	main.py->run_test_chave: 	 New max host on: 373120 at 9300168 sec.
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE4 turned ON
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A02086A, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41480719, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4373081A, from NODE4
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE4 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4696087D, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4B8D0831, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3FB60808, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-458C07D5, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5A7D09B8, from NODE5
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE4 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9303152, lastCicle:9304000, len(op_dict):816
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:512
[INFO] 	main.py->run_test_chave: 	 New max host on: 41795 at 9303152 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-32A006E1, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3B2106D7, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4226089D, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-42BF0807, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4943084C, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4974093B, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41F108EE, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4D0E0965, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4E87095B, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-479C0873, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE4 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-555809BD, from NODE4
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9321051, lastCicle:9322000, len(op_dict):805
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:512
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3AC80795, from NODE6
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3B5507F7, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-51B9089C, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-406807E2, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9355502, lastCicle:9356000, len(op_dict):801
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:512
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9356076, lastCicle:9358000, len(op_dict):790
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:523
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-34960676, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-368806B2, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-414F07EC, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2B7A04EC, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A380753, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3ACF05D5, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-42C0080C, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-443308E7, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4DBB0915, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4FEC0834, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4C3E09C9, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5BAA0A07, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9358288, lastCicle:9360000, len(op_dict):761
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:540
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2AFE055C, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2DC805F4, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3EA80816, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3FA60785, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4332070A, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43C807D6, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4E920855, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-52070A58, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-56B00966, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-57EF095B, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39110754, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A30085C, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41BD07BF, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-443207E8, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-508809C9, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-56F70921, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9363727, lastCicle:9364000, len(op_dict):745
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:540
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9365333, lastCicle:9366000, len(op_dict):743
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:542
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9366462, lastCicle:9368000, len(op_dict):742
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:543
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9390567, lastCicle:9392000, len(op_dict):741
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:544
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9442268, lastCicle:9444000, len(op_dict):740
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:545
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-31930622, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3EFB07AE, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-503108FF, from NODE6
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-485B085C, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9447037, lastCicle:9448000, len(op_dict):736
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:545
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9449778, lastCicle:9450000, len(op_dict):735
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:546
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-541C0920, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4409081B, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9459997, lastCicle:9460000, len(op_dict):733
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:546
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-42980715, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-450308C1, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A1307AE, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9460918, lastCicle:9462000, len(op_dict):730
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:546
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3BE106C6, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E340798, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-50BC0A1A, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9464942, lastCicle:9466000, len(op_dict):727
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:546
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E9607D4, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9466505, lastCicle:9468000, len(op_dict):725
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:547
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9468415, lastCicle:9470000, len(op_dict):723
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:549
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C010845, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9470513, lastCicle:9472000, len(op_dict):721
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:550
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-429408E2, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9472630, lastCicle:9474000, len(op_dict):719
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:551
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9484427, lastCicle:9486000, len(op_dict):716
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:554
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9487932, lastCicle:9488000, len(op_dict):715
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:555
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A3F07F0, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9529385, lastCicle:9530000, len(op_dict):714
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:555
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44CE07E5, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9530858, lastCicle:9532000, len(op_dict):706
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:562
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-31F005F7, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9537431, lastCicle:9538000, len(op_dict):705
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:562
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9540749, lastCicle:9542000, len(op_dict):704
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:563
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4151077F, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-420F07E8, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A520956, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4B88082A, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-465307AC, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9559413, lastCicle:9560000, len(op_dict):699
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:563
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9568220, lastCicle:9570000, len(op_dict):698
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:564
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9576725, lastCicle:9578000, len(op_dict):697
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:565
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-386305F2, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4F970967, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9626464, lastCicle:9628000, len(op_dict):695
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:565
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9632016, lastCicle:9634000, len(op_dict):685
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:575
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-349D05DD, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C9006B5, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-485608EE, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-49DF0822, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4D490814, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-57F609D4, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-35EA05FE, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-45070778, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-486007F7, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-649D0AA5, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9661612, lastCicle:9662000, len(op_dict):675
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:575
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-36E306AA, from NODE0
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9664416, lastCicle:9666000, len(op_dict):674
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:575
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9671855, lastCicle:9672000, len(op_dict):673
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:576
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4CA90866, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9708127, lastCicle:9710000, len(op_dict):672
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:576
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9726109, lastCicle:9728000, len(op_dict):671
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:577
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9730297, lastCicle:9732000, len(op_dict):670
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:578
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-41CF0692, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9795703, lastCicle:9796000, len(op_dict):669
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:578
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4BF80875, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9796565, lastCicle:9798000, len(op_dict):667
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:579
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-39D50708, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40F607BE, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-494B08DF, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-555009B6, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9806778, lastCicle:9808000, len(op_dict):659
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:583
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9814545, lastCicle:9816000, len(op_dict):658
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:584
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-487808B3, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:9900222, lastCicle:9902000, len(op_dict):656
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:585
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48710958, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10076764, lastCicle:10078000, len(op_dict):655
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:585
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-51F3097A, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10141536, lastCicle:10142000, len(op_dict):654
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:585
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10142073, lastCicle:10144000, len(op_dict):634
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:605
[INFO] 	main.py->run_test_chave: 	 New max host on: 476129 at 10142073 sec.
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE4 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10150637, lastCicle:10152000, len(op_dict):621
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:618
[INFO] 	main.py->run_test_chave: 	 New max host on: 52395 at 10150637 sec.
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10152703, lastCicle:10154000, len(op_dict):620
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:619
[INFO] 	main.py->run_test_chave: 	 New max host on: 52495 at 10152703 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-35CF078E, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-376E067C, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-377A0623, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47F10897, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4C3408B3, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4CD60896, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4F560918, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-50FA08E7, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5AB00A0E, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4D5E08F5, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-34F605E6, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10154499, lastCicle:10156000, len(op_dict):609
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:619
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-496108BA, from NODE4
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10227801, lastCicle:10228000, len(op_dict):607
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:620
[INFO] 	main.py->run_test_chave: 	 New max host on: 52595 at 10227801 sec.
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-253D0558, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-34680728, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-390206CD, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A150654, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3B820720, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3B9C069B, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E4B06EA, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3F2D07AC, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40240652, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40700852, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-45B10906, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE4 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-463B07D1, from NODE4
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-464206F7, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-476F080A, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47D80815, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-541A0947, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-58CD0A0D, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-33A607F1, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-34BC06FC, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-42340760, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4565087D, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47130868, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-51340956, from NODE0
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-56060A8A, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10229510, lastCicle:10230000, len(op_dict):583
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:620
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-29FB05F5, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE0 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-320F06D1, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A920758, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C9B07CF, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3DC40742, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3EAC082E, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-460408EB, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-52680A04, from NODE5
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE5 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5DA10979, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10230287, lastCicle:10232000, len(op_dict):574
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:620
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4EE4091E, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10232368, lastCicle:10234000, len(op_dict):572
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:621
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10234008, lastCicle:10236000, len(op_dict):570
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:623
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44BF07E2, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10251104, lastCicle:10252000, len(op_dict):568
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:624
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10270240, lastCicle:10272000, len(op_dict):567
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:625
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-406C07CE, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10309494, lastCicle:10310000, len(op_dict):566
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:625
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10311746, lastCicle:10312000, len(op_dict):565
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:626
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10406992, lastCicle:10408000, len(op_dict):562
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:629
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10415969, lastCicle:10416000, len(op_dict):561
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:630
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-33C606E3, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10657388, lastCicle:10658000, len(op_dict):560
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:630
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10658096, lastCicle:10660000, len(op_dict):558
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:632
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-404507B4, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10660858, lastCicle:10662000, len(op_dict):556
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:633
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-498308EC, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10673926, lastCicle:10674000, len(op_dict):555
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:633
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3FCE07BC, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3FEC0709, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4B760997, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4E6908C1, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10674437, lastCicle:10676000, len(op_dict):551
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:633
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47020790, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4CE008EB, from NODE6
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE6 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3BD30801, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10680920, lastCicle:10682000, len(op_dict):548
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:633
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE6 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10682742, lastCicle:10684000, len(op_dict):547
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:634
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10698841, lastCicle:10700000, len(op_dict):543
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:638
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-394F0680, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10705045, lastCicle:10706000, len(op_dict):542
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:638
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4AE10878, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10745607, lastCicle:10746000, len(op_dict):541
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:638
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-409E06D2, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10763437, lastCicle:10764000, len(op_dict):540
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:638
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10765158, lastCicle:10766000, len(op_dict):539
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:639
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46C90870, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10766947, lastCicle:10768000, len(op_dict):537
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:640
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5AD609CB, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:10832041, lastCicle:10834000, len(op_dict):536
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:640
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11264911, lastCicle:11266000, len(op_dict):535
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:641
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11372713, lastCicle:11374000, len(op_dict):534
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:642
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11437999, lastCicle:11438000, len(op_dict):533
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:643
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-448E08B6, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11441203, lastCicle:11442000, len(op_dict):532
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:643
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4C8007EF, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11443324, lastCicle:11444000, len(op_dict):531
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:643
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11446440, lastCicle:11448000, len(op_dict):528
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:646
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2B5906C0, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-527007DD, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11478995, lastCicle:11480000, len(op_dict):526
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:646
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CB206FD, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11526550, lastCicle:11528000, len(op_dict):525
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:646
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4ADC0863, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11560224, lastCicle:11562000, len(op_dict):523
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:647
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-40570787, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11618411, lastCicle:11620000, len(op_dict):521
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:648
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11654740, lastCicle:11656000, len(op_dict):520
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:649
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E6C06D8, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11740078, lastCicle:11742000, len(op_dict):519
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:649
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-51820A10, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11863851, lastCicle:11864000, len(op_dict):517
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:650
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11865802, lastCicle:11866000, len(op_dict):516
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:651
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E800643, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11870937, lastCicle:11872000, len(op_dict):515
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:651
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11880721, lastCicle:11882000, len(op_dict):514
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:652
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43EC08F0, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11882409, lastCicle:11884000, len(op_dict):513
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:652
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11892042, lastCicle:11894000, len(op_dict):512
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:653
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11966589, lastCicle:11968000, len(op_dict):511
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:654
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11968538, lastCicle:11970000, len(op_dict):509
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:656
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11970101, lastCicle:11972000, len(op_dict):508
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:657
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4FCB0980, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:11975961, lastCicle:11976000, len(op_dict):506
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:658
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-45B8084C, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12033171, lastCicle:12034000, len(op_dict):505
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:658
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4B1B087C, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-481207D7, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12050897, lastCicle:12052000, len(op_dict):503
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:658
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12060696, lastCicle:12062000, len(op_dict):502
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:659
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE5 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12062288, lastCicle:12064000, len(op_dict):500
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:661
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12064529, lastCicle:12066000, len(op_dict):499
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:662
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-358506B5, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12066662, lastCicle:12068000, len(op_dict):498
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:662
[DEBUG] 	Physical.py->force_set_host_on: 	 NEW state:NODE0 turned ON
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12082667, lastCicle:12084000, len(op_dict):497
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:663
[INFO] 	main.py->run_test_chave: 	 New max host on: 530133 at 12082667 sec.
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE0 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-34D4077C, from NODE0
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4C3C08E6, from NODE5
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4EBB0941, from NODE6
[DEBUG] 	Physical.py->set_host_off: 	 		NEW STATE:NODE5 turned:OFF
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E4B0819, from NODE5
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12126890, lastCicle:12128000, len(op_dict):493
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:663
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12149004, lastCicle:12150000, len(op_dict):492
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:664
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47820856, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-36A40631, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12176431, lastCicle:12178000, len(op_dict):486
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:668
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-50340872, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12209398, lastCicle:12210000, len(op_dict):485
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:668
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12211124, lastCicle:12212000, len(op_dict):484
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:669
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3746072F, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4C760828, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12212127, lastCicle:12214000, len(op_dict):481
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:670
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2B6E0665, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-36020684, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12215556, lastCicle:12216000, len(op_dict):475
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:674
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12217170, lastCicle:12218000, len(op_dict):474
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:675
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-55C409D4, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12218700, lastCicle:12220000, len(op_dict):473
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:675
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-38E20692, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12225464, lastCicle:12226000, len(op_dict):472
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:675
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12233339, lastCicle:12234000, len(op_dict):470
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:677
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-361E06E8, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4232078E, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12235541, lastCicle:12236000, len(op_dict):468
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:677
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-32FE0582, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-405A07C4, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12236779, lastCicle:12238000, len(op_dict):465
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:678
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4BCA0921, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12389593, lastCicle:12390000, len(op_dict):464
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:678
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12466909, lastCicle:12468000, len(op_dict):463
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:679
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12490258, lastCicle:12492000, len(op_dict):462
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:680
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3019065E, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12492554, lastCicle:12494000, len(op_dict):460
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:681
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3F3B0805, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12578865, lastCicle:12580000, len(op_dict):455
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:685
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3F1A0760, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12580328, lastCicle:12582000, len(op_dict):454
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:685
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4E120975, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12662157, lastCicle:12664000, len(op_dict):451
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:687
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C9C06FF, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-35EC05E3, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12734023, lastCicle:12736000, len(op_dict):447
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:689
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-52BF0A1A, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4994086C, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12738039, lastCicle:12740000, len(op_dict):444
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:690
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12740240, lastCicle:12742000, len(op_dict):443
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:691
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A1407AD, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CFE0753, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43DB086C, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3F4B07B9, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-50480916, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3B4106D4, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4106073D, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4E05087E, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4C49078B, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12742257, lastCicle:12744000, len(op_dict):430
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:695
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-457C0778, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12745759, lastCicle:12746000, len(op_dict):421
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:703
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4BEF0818, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A2008F8, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48810828, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5C0D0AFC, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4C0608BE, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12821053, lastCicle:12822000, len(op_dict):416
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:703
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12824678, lastCicle:12826000, len(op_dict):412
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:707
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3979068E, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:12837738, lastCicle:12838000, len(op_dict):411
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:707
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2E34054C, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4F290A07, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-43CC0736, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4B1E0813, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13076820, lastCicle:13078000, len(op_dict):407
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:707
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13097930, lastCicle:13098000, len(op_dict):406
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:708
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-44300906, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13170484, lastCicle:13172000, len(op_dict):405
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:708
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13181125, lastCicle:13182000, len(op_dict):404
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:709
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-372207D0, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13183668, lastCicle:13184000, len(op_dict):403
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:709
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13212445, lastCicle:13214000, len(op_dict):402
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:710
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13217694, lastCicle:13218000, len(op_dict):401
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:711
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-448B089B, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13247968, lastCicle:13248000, len(op_dict):400
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:711
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13252052, lastCicle:13254000, len(op_dict):399
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:712
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-54AD0957, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13254819, lastCicle:13256000, len(op_dict):397
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:713
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3CBF073E, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13256001, lastCicle:13258000, len(op_dict):395
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:714
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47E30865, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C870775, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13264598, lastCicle:13266000, len(op_dict):391
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:716
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3C2D071B, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13269637, lastCicle:13270000, len(op_dict):388
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:718
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-5624099E, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13271595, lastCicle:13272000, len(op_dict):387
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:718
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13272075, lastCicle:13274000, len(op_dict):386
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:719
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4CC10816, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3969079C, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13334740, lastCicle:13336000, len(op_dict):383
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:720
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13336851, lastCicle:13338000, len(op_dict):382
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:721
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13338264, lastCicle:13340000, len(op_dict):381
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:722
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-47CF095B, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13340640, lastCicle:13342000, len(op_dict):380
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:722
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-419708CC, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13346067, lastCicle:13348000, len(op_dict):378
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:723
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13350104, lastCicle:13352000, len(op_dict):377
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:724
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A360827, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13354542, lastCicle:13356000, len(op_dict):376
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:724
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-55FC08F1, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13356431, lastCicle:13358000, len(op_dict):375
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:724
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13360343, lastCicle:13362000, len(op_dict):374
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:725
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3E7B06D8, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:13522101, lastCicle:13524000, len(op_dict):373
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:725
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-402B0732, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:14547947, lastCicle:14548000, len(op_dict):372
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:725
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:14552540, lastCicle:14554000, len(op_dict):371
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:726
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3DD3073D, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:14559417, lastCicle:14560000, len(op_dict):370
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:726
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3903068A, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-46560849, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:14560158, lastCicle:14562000, len(op_dict):366
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:728
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-37CD0610, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2D1F0589, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:14562469, lastCicle:14564000, len(op_dict):362
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:730
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-33DC0615, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4A5308C9, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:14564031, lastCicle:14566000, len(op_dict):356
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:734
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-45B40819, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-48CC07A0, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:14566061, lastCicle:14568000, len(op_dict):352
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:736
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-2BA70574, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-473F090A, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:14568144, lastCicle:14570000, len(op_dict):348
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:738
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3FE80767, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3EFA07B2, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3F2007F1, from NODE6
[DEBUG] 	main.py->run_test_chave: 	 Final:CHAVE last arrival:14570116, lastCicle:14572000, len(op_dict):342
[ERROR] 	Datacenter.py->each_cycle_get_hosts_on: 	 SIZE OF HOST_LIST:741
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-4D0B08C9, from NODE6
[DEBUG] 	Datacenter.py->deallocate_on_host: 	 			D:i-3A650634, from NODE6
